POST http://localhost:8080/studentDetails/register
Content-Type: application/json

{
  "fullName": "Rahul Sharma",
  "email": "rahul@gmail.com",
  "phoneNumber": "9876543210",
  "rollNo": "0832CS211001",
  "branch": "CS",
  "year": "2nd Year"
}